django_travelplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('travels/', views.Travel_List.as_view(), name='travel_list'),
    path('travels/new', views.travel_create, name='travel_create'),
    path('travels/<int:pk>', views.travel_detail, name='travel_detail'),
    path('travels/<int:pk>/update', views.Travel_Update.as_view(), name='travel_update'),
    path('travels/<int:pk>/delete', views.Travel_Delete.as_view(), name='travel_delete'),

    path('travels/<int:pk>/itineraries/new', views.Itinerary_Create.as_view(), name='itinerary_create'),
    path('travels/<int:pk>/itineraries/<int:itinerary_id>/update', views.itinerary_update, name='itinerary_update'),
    path('travels/<int:pk>/itineraries/<int:itinerary_id>/delete', views.itinerary_delete, name='itinerary_delete'),

    path('travels/<int:pk>/checklists', views.checklist_list, name='checklist_list'),
    path('travels/<int:pk>/checklists/<int:item_id>/completed', views.is_completed, name="is_completed"),
    path('travels/<int:pk>/checklists/<int:item_id>/notdone', views.is_not_done, name="is_not_done"),
    path('travels/<int:pk>/checklists/<int:item_id>/update', views.checklist_update, name="checklist_update"),
    path('travels/<int:pk>/checklists/<int:item_id>/delete', views.checklist_delete, name="checklist_delete"),

    path('travels/<int:pk>/comments/<int:comment_id>/update', views.comment_update, name='comment_update'),
    path('travels/<int:pk>/comments/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),

    path('destinations/', views.Destination_List.as_view(), name='destination_list'),
    path('destinations/new', views.Destination_Create.as_view(), name='destination_create'),
    path('destinations/<int:pk>', views.Destination_Detail.as_view(), name='destination_detail'),
    path('destinations/<int:pk>/update', views.Destination_Update.as_view(), name='destination_update'),
    path('destinations/<int:pk>/delete', views.Destination_Delete.as_view(), name='destination_delete'),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup_view, name="signup"),

    path('user/<username>', views.profile, name='profile'),
    path('user/<int:pk>/update', views.Profile_Update.as_view(), name='profile_update'),

    # path('users/', views.Users.as_view(), name='users')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    
    profile_image = models.ImageField(upload_to = "profile_images/", blank=True, null=True)
    travel_bucket_list = ArrayField(models.CharField(max_length = 250), blank = True, null=True)

CONTINENT_CHOICES = {
    ("Africa", "Africa"),
    ("Antarctica", "Antarctica"),
    ("Asia", "Asia"),
    ("Europe", "Europe"),
    ("North America", "North America"),
    ("Oceania", "Oceania"),
    ("Sourth America", "South America"),
}

class Destination(models.Model):

    city = models.CharField(max_length = 50)
    country = models.CharField(max_length = 50)
    continent = models.CharField(max_length= 50, choices= CONTINENT_CHOICES, null=True)
    image = models.ImageField(upload_to = "destination_images/", null=True, blank=True)
    description = models.TextField()
    things_to_do = ArrayField(models.CharField(max_length = 250), blank = True)

    def __str__(self):
        return self.city

    class Meta:
        ordering = ['country']

class Tag(models.Model):

    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Travel(models.Model):

    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to = "travel_images/", null=True, blank=True)
    destinations = models.ManyToManyField(Destination, blank=True)
    departure_date = models.DateField(auto_now = False, auto_now_add = False)
    return_date = models.DateField(auto_now = False, auto_now_add = False)
    things_to_do = ArrayField(models.CharField(max_length = 250), blank = True, null=True)
    budget = models.IntegerField()
    travelers = models.ManyToManyField(CustomUser)
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['departure_date']

class Itinerary(models.Model):

    day = models.IntegerField()
    date = models.DateField(auto_now = False, auto_now_add = False)
    destination = models.ForeignKey(Destination, related_name='itineraries', on_delete = models.CASCADE, null=True, blank=True)
    transportation = models.CharField(max_length=250)
    accomodation = models.CharField(max_length=250)
    things_to_do = ArrayField(models.CharField(max_length=250))
    meals = ArrayField(models.CharField(max_length=50))
    daily_budget = models.IntegerField(default = 0)
    travel = models.ForeignKey(Travel, related_name='itineraries', on_delete = models.CASCADE)

    def __str__(self):
        return 'Day' + str(self.day) + '_'+str(self.travel)
    
    class Meta:
        ordering = ['date']

CATEGORY_CHOICES = {
    ("To Confirm List", "To Confirm List"), 
    ("To Do List", "To Do List"),
    ("Packing List", "Packing List"), 
}

PRIORITY_CHOICES = {
    ("High", "High"), 
    ("Medium", "Medium"), 
    ("Low", "Low"), 
    ("None", "None")
}

class List(models.Model):

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    item = models.CharField(max_length=250)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, blank=True)
    is_completed = models.BooleanField(default = False)
    due_date = models.DateField(auto_now = False, auto_now_add = False, blank=True, null=True)
    travel = models.ForeignKey(Travel, related_name='lists', on_delete=models.CASCADE)

    def __str__(self):
        return self.item

    class Meta:
        ordering = ['category', 'is_completed']

class Comment(models.Model):

    text = models.TextField()
    author = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    travel = models.ForeignKey(Travel, related_name='comments', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return 'Comment' + str(self.pk) + '_'+ str(self.travel)

main_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from .models import CustomUser, Travel, Itinerary, Destination, Comment, Tag, List
from .forms import CustomUserCreationForm, CustomUserChangeForm, ItineraryForm, CommentForm, TravelForm, ListForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import get_user_model


# Create your views here.

class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['destinations'] = Destination.objects.order_by('?')[:4]
        context['travels'] = Travel.objects.order_by('?')[:4]
        return context

class Travel_List(TemplateView):
    template_name = 'travel_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        context['users'] = CustomUser.objects.all()
        title = self.request.GET.get("title")
        tag = self.request.GET.get("tag")
        if title != None:
            context['travels'] = Travel.objects.filter(title__icontains=title)
            context['header'] = f"Searching for {title}"
        elif tag !=None:
            context['travels'] = Travel.objects.filter(tags__name__icontains=tag)
            context['header'] = f"Searching for {tag}"
        else:
            context['travels'] = Travel.objects.all()
            context['header'] = "All Travels"
        return context

@login_required
def travel_create(request):
    form = TravelForm(request.POST, request.FILES)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            form.instance.travelers.add(str(request.user.pk))
            tags = form.cleaned_data['tags'].split(',')
            for tag in tags:
                tag=tag.strip().lower()
                if '#' in tag:
                    tag = tag.replace('#', '')
                if len(tag) != 0:
                    tag, created = Tag.objects.get_or_create(name=tag)
                    form.instance.tags.add(tag)
            destinations = form.cleaned_data['destinations']
            for destination in destinations:
                form.instance.destinations.add(destination)
            return HttpResponseRedirect("/travels/")
    return render(request, 'travel_create.html', {'form':form})

def travel_detail(request, pk):
    travel = Travel.objects.get(pk = pk)
    lists = List.objects.filter(travel = pk)
    packing_list = lists.filter(category__icontains= 'Packing')
    confirm_list = lists.filter(category__icontains = 'confirm')
    todo_list = lists.filter(category__icontains = 'to do')
    list_form = ListForm(request.POST)
    comment_form = CommentForm(request.POST)
    if request.method == "POST":
        if list_form.is_valid():
            list_form.instance.travel = travel
            list_form.save()
            return HttpResponseRedirect("/travels/"+str(pk))
        if comment_form.is_valid():
            comment_form.instance.author = request.user
            comment_form.instance.travel = travel
            comment_form.save()
            return HttpResponseRedirect("/travels/"+str(pk))
    return render(request, 'travel_detail.html', {'travel': travel, 'list_form':list_form, 'comment_form':comment_form, 'packing_list': packing_list, 'confirm_list': confirm_list, 'todo_list':todo_list})

@login_required
def comment_update(request, pk, comment_id):
    comment = Comment.objects.get(id=comment_id)
    form = CommentForm(request.POST or None, instance = comment)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/travels/"+str(pk))
    return render(request, 'comment_update.html', {'comment':comment, 'form':form})

@login_required
def comment_delete(request, pk, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return HttpResponseRedirect("/travels/"+str(pk))

@method_decorator(login_required, name='dispatch')
class Travel_Update(UpdateView):
    model = Travel
    # fields = '__all__'
    form_class = TravelForm
    template_name = 'travel_update.html'
    # form_class = TravelForm
    
    def get_success_url(self):
        return reverse('travel_detail', kwargs={'pk': self.object.pk})

    def get_initial(self):
        taglist = Tag.objects.filter(travel = self.object.pk).values_list('name', flat=True)
        return {"tags": ', '.join(taglist)}

    def form_valid(self, form):
        self.object.tags.clear()
        self.object = form.save(commit=False)
        tags = form.cleaned_data['tags'].split(',')
        for tag in tags:
            tag=tag.strip().lower()
            if '#' in tag:
                tag = tag.replace('#', '')
            if len(tag) != 0:
                tag, created = Tag.objects.get_or_create(name=tag)
                self.object.tags.add(tag)
        self.object.save()
        return super(Travel_Update, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class Travel_Delete(DeleteView):
    model = Travel
    template_name = 'travel_delete_confirmation.html'
    success_url = '/travels/'

@method_decorator(login_required, name='dispatch')
class Itinerary_Create(CreateView):
    model = Itinerary
    fields = '__all__'
    template_name = 'itinerary_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        travel = self.kwargs.get("pk")
        context['travel'] = Travel.objects.get(pk=travel)
        return context

    def get_initial(self):
        return {"travel": self.kwargs.get("pk")}

    def get_success_url(self):
        return reverse('travel_detail', kwargs={'pk': self.object.travel.id})
    
    def from_valid(self, form):
        self.object = form.save(commit = False)
        self.object.travel = self.request.travel
        self.object.save()

@login_required
def itinerary_update(request, pk, itinerary_id):
    itinerary = Itinerary.objects.get(id=itinerary_id)
    travel = Travel.objects.get(pk=pk)
    form = ItineraryForm(request.POST or None, instance = itinerary)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/travels/"+str(pk))
    return render(request, 'itinerary_update.html', {'itineray':itinerary, 'form':form, 'travel':travel})

@login_required
def itinerary_delete(request, pk, itinerary_id):
    itinerary = Itinerary.objects.get(id=itinerary_id)
    if request.method == "POST":
        itinerary.delete()
        return HttpResponseRedirect("/travels/"+str(pk))
    return render(request, "itinerary_delete_confirmation.html", {'itinerary':itinerary})

class Destination_List(TemplateView):
    template_name = 'destination_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city = self.request.GET.get("city")
        continent = self.request.GET.get("continent")
        if city != None:
            context['destinations'] = Destination.objects.filter(city__icontains=city)
            context['header'] = f"Searching for {city}"
            context['nav'] = f"{city}"
        elif continent !=None:
            context['destinations'] = Destination.objects.filter(continent__icontains=continent)
            context['header'] = f"Searching for {continent}"
            context['nav'] = f"{continent}"
        else:
            context['destinations'] = Destination.objects.all()
            context['header'] = "All Destinations"
            context['nav'] = "All"
        return context

@method_decorator(login_required, name='dispatch')
class Destination_Create(CreateView):
    model = Destination
    fields = '__all__'
    template_name = 'destination_create.html'
    success_url = "/destinations/"

class Destination_Detail(DetailView):
    model = Destination
    template_name = 'destination_detail.html'

@method_decorator(login_required, name='dispatch')
class Destination_Update(UpdateView):
    model = Destination
    fields = '__all__'
    template_name = 'destination_update.html'
    
    def get_success_url(self):
        return reverse('destination_detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class Destination_Delete(DeleteView):
    model = Destination
    template_name = 'destination_delete_confirmation.html'
    success_url = "/destinations/"

def checklist_list(request, pk):
    travel = Travel.objects.get(pk = pk)
    lists = List.objects.filter(travel = pk)
    packing_list = lists.filter(category__icontains= 'Packing')
    confirm_list = lists.filter(category__icontains = 'Confirm')
    todo_list = lists.filter(category__icontains = 'to do')
    list_form = ListForm(request.POST)
    if request.method == "POST":
        if list_form.is_valid():
            list_form.instance.travel = travel
            list_form.save()
            return HttpResponseRedirect("/travels/"+str(pk)+"/checklists")
    return render(request, 'checklist_list.html', {'travel': travel, 'list_form':list_form, 'packing_list': packing_list, 'confirm_list': confirm_list, 'todo_list':todo_list})

@login_required
def is_completed(request, pk, item_id):
    list_item = List.objects.get(id= item_id)
    list_item.is_completed = True
    list_item.save()
    return HttpResponseRedirect('/travels/'+str(pk)+"/checklists")

def is_not_done(request, pk, item_id):
    list_item = List.objects.get(id= item_id)

main_app/templates/comment_update.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="create-page-h1">Comment Edit Page</h1>
    <div class="create-form-div">
        <form class="comment-edit-form" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" />
            <div>
                <a class="form-cancel" href="{% url 'travel_detail' comment.travel.pk %}">Cancel</a>
                <a class="form-cancel" href="{% url 'comment_delete' pk=comment.travel.pk comment_id=comment.id %}">Delete</a>
            </div>
        </form>
    </div>

{% endblock %}

main_app/templates/destination_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="pagetop-nav">
    <a href="{% url 'destination_list' %}">Destinations</a> / <a href="{% url 'destination_list' %}?continent={{destination.continent}}">{{destination.continent}} </a> / <a href="">{{destination.country}}</a> / <a href="">{{destination.city}}</a>
</div>

    <!-- <h1>Destination Detail Page</h1> -->
        <div class="destination-detail-header">
            {% if destination.image %}
            <img class="destination-detail-header-img" src="{{destination.image.url}}" alt="{{destination.city}}">
            {% endif %}
        </div>
        <div class="detail-section destination-detail-content">
            <h2>{{destination.city}}</h2>
            <h3>{{destination.continent}} / {{destination.country}}</h3>
            <p>{{destination.description}}</p>
            <h3>Things To Do</h3>
            <ul>
                {% for thing_to_do in destination.things_to_do %}
                    <li><p>{{thing_to_do}}</p></li>
                {% endfor %}
            </ul>
            <div>
                <a href="{% url 'destination_update' destination.id %}"><button class="travel-edit-delete-btn">Edit</button></a>
                <a href="{% url 'destination_delete' destination.id %}"><button class="travel-edit-delete-btn">Delete</button></a>
            </div>
        </div>

        <div class="detail-section">
            <a href="{% url 'travel_create' %}">
                <h3 class="add-btn">Start Travel Plan</h3>
            </a>
        </div>

        <div class="detail-section">
            <h2>Travels</h2>
            <div class="destination-travel-list">
                {% for travel in destination.travel_set.all %}
                    <div class="travel-card-content">
                        <a href="{% url 'travel_detail' travel.pk %}">
                            <div class="travel-card-img">
                                {% if travel.image %}
                                    <img class="travel-img" src="{{travel.image.url}}" alt="{{travel.title}}">
                                {% else %}
                                    <img class="travel-img" src="{% static 'images/simon-maage-C9dhUVP-o6w-unsplash.jpg' %}" alt="">
                                {% endif %}
                            </div>
                        <div class="travel-card-text">
                            <h3>{{travel.title}}</h3>
                        </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        
        <div class="detail-section">
            <h2>Itineraries</h2>
            {% for itinerary in destination.itineraries.all %}
                <a href="{% url 'travel_detail' itinerary.travel.pk %}">
                    <p>{{itinerary.travel.title}} Day{{itinerary.day}}</p>
                </a>
            {% endfor %}
        </div>
    
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <!-- <h1>Travel Planner Home Page</h1> -->
    <div class="home-header">
        <img class="home-header-img" src="https://images.unsplash.com/photo-1543993454-23889b990266?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3866&q=80" alt="home header img">
        <div class="home-header-text">
            <h1>Plan Your Travel</h1>
            <h2>Start planning travel with your people<br>
                and share the precious memories</h2>
            <a href="{% url 'travel_create' %}"><button class="home-startplan-btn">Start Planning</button></a>
        </div>
    </div>

    <div class="home-list">
        <div class="home-list-header">
            <h2>Destinations</h2>
            <a href="/destinations">view all</a>
        </div>
        <div class="home-list-flex">
            {% for destination in destinations%}
                <div class="home-destination-card-content">
                    <a href="{% url 'destination_detail' destination.id %}">
                        <div class="home-destination-card-img">
                            {% if destination.image %}
                            <img class="home-destination-img" src="{{destination.image.url}}" alt="{{destination.city}}">
                            {% endif %}
                        </div>
                        <div class="home-destination-card-text">
                            <h3>{{destination.city}}</h3>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="home-list">
        <div class="home-list-header">
            <h2>Travels</h2>
            <a href="/travels">view all</a>
        </div>
        <div class="home-list-flex">
            {% for travel in travels%}
                <div class="home-travel-card-content">
                    <a href="{% url 'travel_detail' travel.pk %}">
                        <div class="home-travel-card-img">
                            {% if travel.image %}
                            <img class="home-travel-img" src="{{travel.image.url}}" alt="{{travel.title}}">
                            {% endif %}
                        </div>
                        <div class="home-travel-card-text">
                            <h3>{{travel.title}}</h3>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

main_app/templates/itinerary_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="pagetop-nav">
    <a href="{% url 'profile' user.username%}">My Travel</a> / <a href="{% url 'travel_detail' travel.pk %}">{{travel.title}}</a> / <a href="">Add Itinerary</a>
</div>

<div class="form-page">
    <div class="form-page-left">
        {% if travel.image %}
        <img class="travel-img" src="{{travel.image.url}}" alt="{{travel.title}}">
        {% else %}
        <img class="travel-img" src="{% static 'images/simon-maage-C9dhUVP-o6w-unsplash.jpg' %}" alt="">
        {% endif %}
        <h1>{{travel.title}}</h1>
        <h3>{{travel.departure_date}}~{{travel.return_date}}</h3>
        <p>Destinations: {{ travel.destinations.all|join:", "}}</p>
        <p>Budget: {{travel.budget}}</p>
        <p>Travelers: {{ travel.travelers.all|join:", "}}</p>
        <p>Itineraries: </p>
        {% for itinerary in travel.itineraries.all %}
            <div class="itinerary-card">
                <span>Day{{itinerary.day}}</span>
                <span>({{itinerary.date}})</span>
                <span>{{itinerary.destination}}</span>
            </div>
        {% endfor %}

</div>
    <div class="form-page-right">
        <h2>Add New Itinerary</h2>
        <form class="create-form" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" />
        </form>
    </div>
</div>

{% endblock %}

main_app/templates/itinerary_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}

<div class="pagetop-nav">
    <a href="{% url 'profile' user.username%}">My Travel</a> / <a href="{% url 'travel_detail' itinerary.travel.pk %}">{{itinerary.travel.title}}</a> / <a href="">Delete Itinerary</a>
</div>

    <h1>Delete Your Travel Itinerary</h1>
    <p>Are you sure you want to delete <strong>{{itinerary.travel.title}} {{itinerary.day}}</strong>?</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes Delete">
    </form>
    <a href="{% url 'travel_detail' itinerary.travel.pk %}"><button>Cancel</button></a>

{% endblock %}

main_app/templates/itinerary_update.html
{% extends 'base.html' %}

{% block content %}

<div class="pagetop-nav">
    <a href="{% url 'profile' user.username%}">My Travel</a> / <a href="{% url 'travel_detail' travel.pk %}">{{travel.title}}</a> / <a href="">Edit Itinerary</a>
</div>

<div class="form-page">
    <div class="form-page-left">
        <h1>Itinerary Update</h1>
        <h3>{{travel.title}} ({{travel.departure_date}}~{{travel.return_date}})</h3>
    </div>
    <div class="form-page-right">
        <form class="create-form" method="post" enctype = "multipart/form-data">
            {% csrf_token %}
            {{form.as_table}}
            <input type="submit" value="Submit" />
            <a class="form-cancel" href="{% url 'travel_detail' travel.pk %}">Cancel</a>
        </form>
    </div>
</div>
    
{% endblock %}

main_app/templates/list_update.html
{% extends 'base.html' %}

{% block content %}

{% for list in lists %}
<p>{{list.item}}</p>
<button class="list-edit">Edit</button>
<form class="list-edit-form" action="" method="post">
    {% csrf_token %}
    {{list_form.as_table}}
    <input type="submit" value="Submit" />
</form>
{% endfor %}


{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="pagetop-nav">
    <a href="{% url 'profile' user.username%}">My Travel</a> / <a href="">{{nav}} ({{travels|length}})</a>
</div>

<div class="list-flex-container">

    <div class="list-flex-nav">
        <div class="list-flex-nav-top">
            {% if user.profile_image %}
            <img class="profile-page-profile-image" src="{{user.profile_image.url}}" alt="">
            {% else %}
            <img  class="profile-page-profile-image" src="{% static 'images/blank-profile-picture.png' %}" alt="">
            {% endif %}
            <h1>{{user.username}}</h1>
            <ul>
                {% for buketlist in user.travel_buket_list %}
                <li>{{bucketlist}}</li>
                {% endfor %}
            </ul>
            {% if user.is_authenticated and user == user.pk%}
            <a class="edit-profile" href="{% url 'profile_update' user.pk %}">
                <img  class="setting-icon" src="{% static 'images/outline_settings_black_24dp.png' %}" alt="">
                <span>Edit Profile</span>
            </a>
            {% endif %}
            <!-- <p>Travel Plans: {{user.travel_set.all|length}}</p> -->
            <div class="list-flex-nav-category">
                <ul class="tag-ul">
                    <li class="{% if nav == 'All Travels' %} active {% endif %}"><a href="{% url 'profile' user.username %}">All</a></li>
                    {% for tag in tags %}
                        <li class="{% if nav == tag.name %} active {% endif %}"><a href="{% url 'profile' user.username %}?tag={{tag}}" name="tag" value="{{tag}}">#{{tag}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% if user.is_authenticated and user is user.username%}
        <div class="list-flex-nav-bottom">
            <a href="{% url 'travel_create' %}">
                <p class="add-btn"> + Start Travel Plan</p>
            </a>
        </div>
        {% endif %}
    </div>

    <div class="list-content">
        <div class="list-flex">
            {% for travel in travels %}
            <div class="profile-travel-card-content">
                <a href="{% url 'travel_detail' travel.pk %}">
                    <div class="travel-card-img">
                        {% if travel.image %}
                        <img class="travel-img" src="{{travel.image.url}}" alt="{{travel.title}}">
                        {% else %}
                        <img class="travel-img" src="{% static 'images/simon-maage-C9dhUVP-o6w-unsplash.jpg' %}" alt="">
                        {% endif %}
                        <div class="profile-travel-card-text">
                            <h2>{{travel.title}}</h2>
                        </div>
                    </div>

                </a>
            </div>
            {% endfor %}
        </div>
    </div>

</div>


{% endblock %}

main_app/templates/profile_update.html
{% extends 'base.html' %}

{% block content %}

<div class="form-page">
    <div class="form-page-left">
        <h1>Profile Update Page</h1>
    </div>

    <div class="form-page-right">
        <form class="create-form profile-update-form" method="post" enctype = "multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" />
            <a class="form-cancel" href="{% url 'profile' user.pk %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="login-page">
        <img class="login-img" src="https://images.unsplash.com/photo-1543993454-23889b990266?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3866&q=80" alt="home header img">
        <div class="login-form">
            <div class="login-msg">
                <h1>Plan Your Travel</h1>
            </div>
            <form class="login-create-form" action="" method="post">
                {% csrf_token %}
                {{form.as_table}}
                <input type="submit" value="Submit">
            </form>
        </div>       
    </div>

{% endblock %}

main_app/templates/users.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% for user in users %}
<p>{{user}}</p>
{% if user.profile_image %}
            <img class="profile-page-profile-image" src="{{user.profile_image.url}}" alt="">
            {% else %}
            <img  class="profile-page-profile-image" src="{% static 'images/blank-profile-picture.png' %}" alt="">
            {% endif %}
<p>Travel Plan Postings: {{user.travel_set.all|length}}</p>
<a href="{% url 'profile' user.username %}">{{user}} Profile Page</a>
{% endfor%}

{% endblock %}